name: Path Filter Example

on:
  push:
    branches:
      - main
      - 20250101-md2blogger-initial-implementation

jobs:
  path-filter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            posts:
              - 'sample/posts/**'
            docs:
              - 'docs/**'

      - name: Print changed files in "posts"
        run: echo "Changed files in posts: ${{ steps.filter.outputs.posts_paths }}"

      - name: Print changed files in "docs"
        run: echo "Changed files in docs: ${{ steps.filter.outputs.docs_paths }}"