name: Path Filter Example

on:
  push:
    branches:
      - main

jobs:
  path-filter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python from .python-version
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Check file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          base: main
          list-files: json
          filters: |
            posts:
              - 'sample/posts/**/*.md'
          ignore-deletions: true # 삭제된 파일 제외

      - name: Upload changed Markdown files to Blogger
        run: |
          # env
          REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY
          echo $REPO_URL
          python3 src/md2blogger.py \
            --files '${{ steps.filter.outputs.posts_files }}' \
            --github_url $REPO_URL \
            --blogger_client_id ${{ secrets.BLOGGER_CLIENT_ID }} \
            --blogger_client_secret ${{ secrets.BLOGGER_CLIENT_SECRET }} \
            --blogger_refresh_token ${{ secrets.BLOGGER_REFRESH_TOKEN }} \
            --blogger_blog_id ${{ secrets.BLOGGER_BLOG_ID }}