name: Markdown to Google Blogger

on:
  push:
    branches:
      - main
      - 20250101-md2blogger-initial-implementation

jobs:
  path-filter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check File changes
        id: change
        uses: dorny/paths-filter@v3
        with:
          filters: |
            posts:
              - 'sample/posts/**'
              # - 'posts/**'

      - name: Print
        run: echo "${{ steps.change.outputs.posts }}"