name: Path Filter Example

on:
  workflow_call:
    inputs:
      blogger_client_id:
        required: true
        type: string
      blogger_client_secret:
        required: true
        type: string
      blogger_refresh_token:
        required: true
        type: string
      blogger_blog_id:
        required: true
        type: string
  push:
    branches:
      - main

jobs:
  path-filter:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout blog post repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: main

      - name: Checkout md2blogger repository
        uses: actions/checkout@v3
        with:
          repository: swellful-life/md2blogger
          ref: main
          path: md2blogger

      - name: Print inputs values
        run: |
          echo "blogger_client_id: ${{ inputs.blogger_client_id }}"
          echo "blogger_client_secret: ${{ inputs.blogger_client_secret }}"
          echo "blogger_refresh_token: ${{ inputs.blogger_refresh_token }}"
          echo "blogger_blog_id: ${{ inputs.blogger_blog_id }}"
      - name: check dirs
        run: |
          ls -la
          ls -la md2blogger
          ls -la md2blogger/src

      - name: Setup Python from .python-version
        uses: actions/setup-python@v4
        with:
          python-version-file: md2blogger/.python-version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r md2blogger/requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Check file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          base: main
          list-files: json
          filters: |
            posts:
              - 'posts/**/*.md'
          ignore-deletions: true

      - name: Upload changed Markdown files to Blogger
        if: steps.filter.outputs.posts != '[]'
        run: |
          # env
          REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY
          echo $REPO_URL
          python3 src/md2blogger.py \
            --files '${{ steps.filter.outputs.posts }}' \
            --github_url $REPO_URL \
            --blogger_client_id ${{ inputs.blogger_client_id }} \
            --blogger_client_secret ${{ inputs.blogger_client_secret }} \
            --blogger_refresh_token ${{ inputs.blogger_refresh_token }} \
            --blogger_blog_id ${{ inputs.blogger_blog_id }}